name: Feature Request
description: Suggest an improvement or a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion.

  - type: textarea
    id: problem
    attributes:
      label: What problem should this solve?
      description: Describe the use case.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What could the feature look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other approaches?

  - type: textarea
    id: context
    attributes:
      label: Additional context
